# Generated by Django 3.1.3 on 2020-11-30 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('idAdresu', models.AutoField(primary_key=True, serialize=False)),
                ('Miasto', models.CharField(max_length=45)),
                ('Ulica', models.CharField(max_length=100)),
                ('KodPocztowy', models.CharField(max_length=45)),
                ('Wojewodztwo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutora', models.AutoField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=75)),
                ('Nazwisko', models.CharField(max_length=75)),
                ('DataUrodzenia', models.DateTimeField()),
                ('Opis', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('idKategorii', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=45)),
                ('Opis', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('idKlienta', models.AutoField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=45)),
                ('Nazwisko', models.CharField(max_length=45)),
                ('czyUser', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Paragon',
            fields=[
                ('idParagonu', models.AutoField(primary_key=True, serialize=False)),
                ('suma', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUsera', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('prac', 'pracownik'), ('kier', 'kierownik')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('idKsiazki', models.AutoField(primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=150)),
                ('cena_netto', models.FloatField()),
                ('rok_wydania', models.DateTimeField()),
                ('cena_brutto', models.FloatField()),
                ('ilosc', models.CharField(max_length=45)),
                ('idAutora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KsiegarniaDB.autor')),
            ],
        ),
    ]
