# Generated by Django 3.1.3 on 2021-01-12 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutora', models.AutoField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=75)),
                ('Nazwisko', models.CharField(max_length=75)),
                ('DataUrodzenia', models.DateTimeField()),
                ('Opis', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('idKategorii', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=45)),
                ('Opis', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('idKategorii',),
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('idKlienta', models.AutoField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=45)),
                ('Nazwisko', models.CharField(max_length=45)),
                ('czyUser', models.BooleanField()),
            ],
            options={
                'ordering': ('idKlienta',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('idUsera', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paragon',
            fields=[
                ('idParagonu', models.AutoField(primary_key=True, serialize=False)),
                ('suma', models.FloatField()),
                ('dataWystawienia', models.DateTimeField(null=True)),
                ('idKlienta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paragon', to='KsiegarniaDB.klient')),
                ('idUsera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paragon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('idParagonu',),
            },
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('idKsiazki', models.AutoField(primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=150)),
                ('cena_netto', models.FloatField()),
                ('rok_wydania', models.DateTimeField()),
                ('cena_brutto', models.FloatField()),
                ('ilosc', models.CharField(max_length=45)),
                ('idAutora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ksiazka', to='KsiegarniaDB.autor')),
                ('idKategorii', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ksiazka', to='KsiegarniaDB.kategoria')),
            ],
            options={
                'ordering': ('idKsiazki',),
            },
        ),
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('idAdresu', models.AutoField(primary_key=True, serialize=False)),
                ('Miasto', models.CharField(max_length=45)),
                ('Ulica', models.CharField(max_length=100)),
                ('KodPocztowy', models.CharField(max_length=45)),
                ('Wojewodztwo', models.CharField(max_length=45)),
                ('idKlienta', models.ManyToManyField(related_name='adres', to='KsiegarniaDB.Klient')),
                ('idUsera', models.ManyToManyField(related_name='adres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('idAdresu',),
            },
        ),
    ]
