# Generated by Django 3.1.3 on 2020-11-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KsiegarniaDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='idKlienta',
            field=models.ManyToManyField(to='KsiegarniaDB.Klient'),
        ),
        migrations.AddField(
            model_name='adres',
            name='idUsera',
            field=models.ManyToManyField(to='KsiegarniaDB.User'),
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='idKategorii',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KsiegarniaDB.kategoria'),
        ),
        migrations.AddField(
            model_name='paragon',
            name='idKlienta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KsiegarniaDB.klient'),
        ),
        migrations.AddField(
            model_name='paragon',
            name='idUsera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KsiegarniaDB.user'),
        ),
    ]
