# Generated by Django 3.1.3 on 2020-11-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsiegarniaDB', '0002_auto_20201130_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email2',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
