# Generated by Django 3.1.3 on 2020-12-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KsiegarniaDB', '0003_auto_20201130_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email2',
        ),
    ]
