# Generated by Django 3.1.3 on 2021-01-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KsiegarniaDB', '0004_auto_20210112_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='czyUser',
        ),
    ]
