# Generated by Django 3.1.3 on 2020-12-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KsiegarniaDB', '0005_paragon_datawystawienia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='idAutora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KsiegarniaDB.autor'),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='idKategorii',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KsiegarniaDB.kategoria'),
        ),
        migrations.AlterField(
            model_name='paragon',
            name='idKlienta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KsiegarniaDB.klient'),
        ),
        migrations.AlterField(
            model_name='paragon',
            name='idUsera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KsiegarniaDB.user'),
        ),
    ]
