# Generated by Django 3.1.3 on 2020-12-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KsiegarniaDB', '0006_auto_20201207_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='idKlienta',
            field=models.ManyToManyField(related_name='adres', to='KsiegarniaDB.Klient'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='idUsera',
            field=models.ManyToManyField(related_name='adres', to='KsiegarniaDB.User'),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='idAutora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ksiazka', to='KsiegarniaDB.autor'),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='idKategorii',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ksiazka', to='KsiegarniaDB.kategoria'),
        ),
        migrations.AlterField(
            model_name='paragon',
            name='idKlienta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paragon', to='KsiegarniaDB.klient'),
        ),
        migrations.AlterField(
            model_name='paragon',
            name='idUsera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paragon', to='KsiegarniaDB.user'),
        ),
    ]
