# Generated by Django 3.1.3 on 2021-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsiegarniaDB', '0008_auto_20201230_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('prac', 'pracownik'), ('kier', 'kierownik'), ('klie', 'klient')], max_length=4),
        ),
    ]
